// <auto-generated />
namespace Booking_Tour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class change_type_column_aaaa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(change_type_column_aaaa));
        
        string IMigrationMetadata.Id
        {
            get { return "202011221146148_change_type_column_aaaa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
