// <auto-generated />
namespace Booking_Tour.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class arlet_table_bills : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(arlet_table_bills));
        
        string IMigrationMetadata.Id
        {
            get { return "202011180916355_arlet_table_bills"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
